### ISSUE TITLE
Kitty terminal emulator support

### ISSUE THREAD

**Issue by TheAvidDev** [slavfox/Cozette#18]
I'm not sure if this font is considered monospace*, but if it is, then it doesn't get recognized by `kitty`. The [`kitty`](https://github.com/kovidgoyal/kitty) terminal emulator is quite picky about what it takes as a monospaced font and it doesn't detect Cozette. A list of fonts that it deems acceptable can be listed with `kitty list-fonts`.

Here's three issues for reference and possible solutions (it seems a common one is the font's `Spacing` parameter): kovidgoyal/kitty#827, kovidgoyal/kitty#557, and ryanoasis/nerd-fonts#268

Regardless of the resolution, thanks for the beautiful font!

*If this font isn't meant to be monospaced, feel free to close this issue.

**Comment by slavfox** [comment]
> If this font isn't meant to be monospaced, feel free to close this issue.

There... isn't really a useful definition of "monospaced" for people to agree on. The BDF font is specified as monospaced with the XLFD spacing property, but Kitty doesn't accept it because it wants a font considered "scalable" by fontconfig. The other fonts don't really have a way, afaict, of specifying they're monospace - it's generally based on whether the characters in the font are all the same width (and in Cozette, they explicitly aren't, because of eg. double-wide emoji), and some more black magic behind the scenes.

I've found https://github.com/microsoft/cascadia-code/issues/118#issuecomment-552788163, which might be relevant. They seem to have solved the problem of a font with mixed-width glyphs not being recognized as monospace, I'll have to try and figure out how.

**Comment by TheAvidDev** [comment]
Ah, alright, I've never delved into fonts or font making so I didn't know about all the fine details. Thanks for trying though, I'm happy to test anything!

**Comment by slavfox** [comment]
I just realized Kitty doesn't support bitmap fonts, so this is a CozetteVector issue, which makes it much easier to fix. I suspect this might've gotten fixed in #14 and could work as of [release 1.8.1](https://github.com/slavfox/Cozette/releases/tag/v.1.8.1). Could you try it out and let me know if it works now?

**Comment by TheAvidDev** [comment]
Oh, I didn't know Kitty doesn't support bitmap fonts, but I've just tried `CozetteVector` and kitty still doesn't detect it. With this new info (about no bitmap support), I don't personally have a need for kitty terminal support but I'm happy to test out any future releases / fixes :)

**Comment by novcn** [comment]
Here's a related issue I opened yesterday without seeing this one https://github.com/kovidgoyal/kitty/issues/2739

Without the patch, I am able to get kitty to render CozetteVector via the below configuration options
![cozette](https://user-images.githubusercontent.com/6252068/83954739-b518f700-a800-11ea-81d3-c1f93cc9cf93.png)

However, as you can see the font is too small for my DPI. @slavfox I'm curious about what your DPI is? I'd really like to use Cozette but might go blind in the process :)

**Comment by slavfox** [comment]
@novcn the font in your screenshot is not Cozette, as can be seen by eg. the `a` glyph and its derivatives. Cozette:
![image](https://user-images.githubusercontent.com/35173529/83956549-9f86ea00-a85f-11ea-95b4-2008e5ed3a05.png)

I'm on a HP Omen X35, 3440x1440 over 35", which comes down to 106.55 PPI. My laptop is 15" 1080p, for 146.86 PPI. I like small fonts :D

If you're looking for a larger bitmap font that still has solid powerline support, I can't recommend [Tamzen](https://github.com/sunaku/tamzen-font/) enough. It's too big for my taste, but might be perfect for you.

I'll add a note with some larger bitmap fonts to the README, since this seems to be a common question. Making a bitmap font with this many glyphs is a _lot_ of work - unlike vector fonts, which can be auto-patched for Nerd Fonts support, I draw each character by hand. I doubt I'm ever going to make larger variants of Cozette for that reason, so the least I can do is refer to some excellent larger bitmap fonts :)

**Comment by TheAvidDev** [comment]
> @novcn the font in your screenshot is not Cozette, as can be seen by eg. the `a` glyph and its derivatives. Cozette:

I think this has to do with your command line. You should probably specify `CozetteVector` not `Cozette` (because Kitty doesn't have bitmap support), although I haven't had success with either, hence this issue.

**Comment by novcn** [comment]
@slavfox thanks for the info! I'll give Tamzen a shot sometime.

Kitty was indeed falling back to `Nimbus Mono`

I was able to get kitty to load `Cozette-otb` using the patched branch mentioned in the kitty issue I linked.

![cozette-otb](https://user-images.githubusercontent.com/6252068/83958484-3f745180-a827-11ea-9422-0608ddcb099a.png)

`CozetteVector` is working for me as well! (Without patched kitty) and the size is perfect and scalable.
![2020-06-06-190831_1324x511_scrot](https://user-images.githubusercontent.com/6252068/83958655-279dcd00-a829-11ea-84c9-38910ed600b2.png)

**Comment by TheAvidDev** [comment]
> I was able to get kitty to load Cozette-otb using the patched branch mentioned in the kitty issue I linked.

Damn, I really wanted this to work, but I tried it as well and it just... _doesn't_ :disappointed: 

Not really sure why, I built both `cozette-otb` and `kitty` from source. I guess this should probably be closed though, since it seems to work for you and other in the kitty thread you linked.

**Comment by slavfox** [comment]
I'd like to leave this open until (if) bitmap font support gets merged into kitty master. Cozette bitmap should work correctly on the new branch, Cozette Vector still doesn't look right in @novcn's screenshot - the bottoms of the glyphs are cut off, although I suspect that's just a Kitty configuration issue, I'd try playing with `adjust_line_height`.

Compare eg. `g`, `p`, and `q` in @novcn's second screencap:
![image](https://user-images.githubusercontent.com/35173529/83958892-5478d100-a877-11ea-9a75-8acff946da0f.png)

To the bitmap version, which renders correctly: 
![image](https://user-images.githubusercontent.com/35173529/83958896-6f4b4580-a877-11ea-975b-ef5c0ce16f46.png)

As far as I can tell, bitmap `Cozette` gets correctly detected as monospace because the bitmap font formats allow me to explicitly define the spacing as monospace, but `CozetteVector`... doesn't, despite having the panose tables set. I think fontconfig might be basing that on individual glyph widths.

@TheAvidDev I didn't realize I never asked for this - are you on Linux or MacOS? novcn is on Mac, so this might be a system-specific problem (kitty uses coretext rather than fontconfig on Mac).

**Comment by novcn** [comment]
I'm actually on Linux @slavfox

**Comment by TheAvidDev** [comment]
I'm on `Arch Linux x86_64 - 5.6.15-arch1-1`. I also have a quick question:
> new branch

Do you mean the `kitty` fork?

**Comment by novcn** [comment]
Based on the creator of Kitty's comment here https://github.com/kovidgoyal/kitty/issues/97#issuecomment-373970232 it doesn't look like bitmap font support will be merged into kitty master FYI.

I'll mess around with the kitty config in a bit to fix Cozette Vector rendering.

**Comment by slavfox** [comment]
Ah, my bad! I assumed it was Mac because of the `.dfont`s 😅 I didn't realize it was possible to get them to work on Linux.

I also misread that fork as being a branch on the upstream `kitty` repo. Yeah, I saw that old issue, just assumed the creator had a change of heart since then. 

Doesn't really look like I can do much more here - I'll add a note about Kitty being incompatible, and a link to the fork, to the README tomorrow, and close this, in that case 😞

**Comment by TheAvidDev** [comment]
Yep, a note about a potential workaround would make sense.

**Comment by TheAvidDev** [comment]
Also about that fork, it doesn't look like that's going to be up forever, a link to the specific commit in that fork is probably wiser in the long term.

**Comment by novcn** [comment]
I'm also on Arch @TheAvidDev 

Here's some more info on my set-up in case it helps you.

```
λ › kitty --version
kitty 0.17.4 created by Kovid Goyal
```

I built Cozette from source off `master` and then moved the `build` dir over to `~/.fonts` where I keep my fonts. I then ran a script I wrote to install them: `~/.fonts/recache`

```bash
#!/bin/bash

fonts_base="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $fonts_base

for font in `ls -d */ | sed 's/\///g'`; do
  echo "found font $fonts_base/$font"
  xset +fp $fonts_base/$font
done

xset fp rehash
fc-cache
fc-cache -fv

cd -
```

Not sure if this is the best way to do things, but worked for me.

**Comment by TheAvidDev** [comment]
Thanks, I'll try it out soon.

**Comment by slavfox** [comment]
I've added notes on `kitty` to the README: https://github.com/slavfox/Cozette/commit/0647b415be6bb9a4877c2c965ef15c3a45285000

**Comment by TheAvidDev** [comment]
Looks good, I also use alacritty and it works great, it's just slow when starting which is why I'd like to switch to kitty. But the rejection of bitmap makes me want to use it less and less.

**Comment by 4e554c4c** [comment]
Hello, sorry to bump but I published an AUR package with a patch that allows Cozette (otb) to be used.
https://aur.archlinux.org/packages/kitty-bitmap/

**Comment by TheAvidDev** [comment]
> Hello, sorry to bump but I published an AUR package with a patch that allows Cozette (otb) to be used.
> https://aur.archlinux.org/packages/kitty-bitmap/

Thanks, I'll try it out -- in the meantime, perhaps you should change the description, etc.

**Comment by slavfox** [comment]
Updated the README; thank you!

**Comment by undefinedDarkness** [comment]
Hope im not being annoying, but what font settings should I use with kitty for cozette? It looks all broken 
![1612764252](https://user-images.githubusercontent.com/38278035/107182580-05d19700-6a03-11eb-8274-8048316fd2e5.png)
```font_size 13
adjust_column_width 1
adjust_line_height 20 ```
works but maybe thats not correct :sweat_smile: , the cursor looks too big too so something is probably wrong

**Comment by clort81** [comment]
Kitty will *NEVER* render the font you specify because the program author has determined he knows better what certain glyphs should look like.
https://github.com/kovidgoyal/kitty/issues/5910
